name: Lua CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.lua"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.lua"

jobs:
  stylua:
    name: Check Lua style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stylua
        uses: baptiste0928/cargo-install@v3
        with:
          crate: stylua
          features: lua54
      - run: stylua --version
      - run: stylua --color always --check ./lua/ ./plugin/ ./tests/

  luacheck:
    name: Lint Lua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: ./lua/
