name: Rust CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "Cargo.lock"
      - "Cargo.toml"
      - ".github/workflows/ci.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "Cargo.lock"
      - "Cargo.toml"
      - ".github/workflows/ci.yml"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] # Windowsは一時的に無効化
        rust: [stable]
        include:
          - os: ubuntu-latest
            lua-name: luajit
            lua-dev: libluajit-5.1-dev
          - os: macos-latest
            lua-name: luajit
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.71.1" # Rust 1.71.1を明示的に指定

      - name: Install LuaJIT (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.lua-name }} ${{ matrix.lua-dev }}

      - name: Install LuaJIT (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install luajit

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          toolchain: "1.71.1"

      - name: Install LuaJIT
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit libluajit-5.1-dev

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.71.1" # zerofromの要件に合わせて更新

      - name: Install LuaJIT
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit libluajit-5.1-dev

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check MSRV
        run: cargo check --all-features

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.71.1"

      - name: Install LuaJIT
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit libluajit-5.1-dev

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check documentation
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --all-features
