name: Rust CI

on:
  push:
    branches:
      - main
    paths:
      - "crates/**/*"
      - "Cargo.lock"
      - "Cargo.toml"
  pull_request:
    branches:
      - main
    paths:
      - "crates/**/*"
      - "Cargo.lock"
      - "Cargo.toml"

jobs:
  tests:
    name: Run Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Run rust tests
        run: cargo test --features luajit

  style:
    name: Check Rust style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Run rustfmt
        run: make ruststylecheck

  lint:
    name: Lint Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.83.0"
          components: clippy, rustfmt
      - name: Run rustfmt
        run: make rustlint
